import { z } from 'zod';

export const LeadSchema = z.object({
    email: z.string().email({ message: "Invalid email address" }),
    vision: z.string().min(10, { message: "Vision description must be at least 10 characters" }),
    budget: z.enum(["starter", "pro", "business", "enterprise"]),
    siteType: z.enum(["blog", "business", "store"])
});

export type LeadFormValues = z.infer<typeof LeadSchema>;

// SOVEREIGN JSON BLUEPRINT SCHEMA
// Note: All fields must be required for OpenAI strict JSON schema compatibility
// Using additionalProperties: true for record/object types to avoid propertyNames issues

export const SectionSchema = z.object({
    id: z.string(),
    type: z.enum([
        "hero",
        "HERO_PRIME",
        "FEATURE_GRID",
        "LOGIC_SERVICES",
        "IMAGE_MUSEUM",
        "TRUST_BAR",
        "PRO_OFFER",
        "SMART_FORM",
        "TEAM_STATION",
        "FAQ_MASTER",
        "PRICE_ENGINE",
        "TESTIMONIAL_STREAM",
        "COUNTDOWN_LOGIC",
        "SOCIAL_ORBIT",
        "features",
        "pricing",
        "testimonials",
        "cta",
        "gallery",
        "benefits",
        "trust_bar",
        "faq",
        "contact",
        "contact_map",
        "about",
        "split",
        "team",
        "services",
        "blog_list",
        "LEGAL_NOTICE",
        "APPOINTMENT_WIDGET",
        "LIVE_PRICING",
        "custom"
    ]),

    content: z.record(z.string(), z.any()),
    styles: z.record(z.string(), z.any()),
    animation: z.enum(["fade-in", "slide-up", "zoom-in", "none"]),
});

export const PageSchema = z.object({
    id: z.string(),
    slug: z.string(),
    name: z.string(),
    description: z.string().optional(),
    layout: z.array(SectionSchema),
    status: z.enum(["draft", "published"]),
    keywords: z.array(z.string()).optional(), // Image search keywords generated by AI
});

export const SiteBlueprintSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    navigation: z.object({
        logo: z.string(),
        links: z.array(z.object({ label: z.string(), href: z.string() })),
        transparent: z.boolean(),
    }),
    theme: z.object({
        primary: z.string(),
        secondary: z.string(),
        accent: z.string(),
        fontFamily: z.string(),
        backgroundColor: z.string().default("#ffffff"),
        textColor: z.string().default("#000000"),
        mode: z.enum(["light", "dark", "industrial", "quantum", "medical", "luxury", "clean", "neon"]),
    }),

    pages: z.record(z.string(), PageSchema), // Mapping of slug -> Page
    layout: z.array(SectionSchema), // Home page layout (for backward compatibility)
    footer: z.object({
        copyright: z.string(),
        links: z.array(z.object({ label: z.string(), href: z.string() })),
        social: z.record(z.string(), z.string()),
    }),
    seo: z.object({
        title: z.string(),
        description: z.string(),
        keywords: z.string(),
        ogImage: z.string().optional(),
        favicon: z.string().optional(),
    }).optional(),
    metadata: z.record(z.string(), z.any()),
    economic_impact: z.object({
        estimated_savings: z.string(),
        valuation: z.number().optional(),
        logic_verified: z.boolean().default(true)
    }),
    ai_insight: z.string().optional(),
    whiteLabel: z.boolean().default(false),
    timestamp: z.string(),
});

export type Section = z.infer<typeof SectionSchema>;
export type SiteBlueprint = z.infer<typeof SiteBlueprintSchema>;

export interface Category {
    id: string;
    name: string;
    slug: string;
}

export interface Post {
    id: string;
    title: string;
    slug: string;
    excerpt: string;
    content: string;
    author: {
        name: string;
        avatar: string;
    };
    date: string;
    category: string;
    image: string;
    tags: string[];
}
